### ISSUE TITLE
slice bounds out of range in FindLongestMatch

### ISSUE THREAD

**Issue by thaustad** [andybalholm/brotli#44]
I don't have a reproducer, but I have a stack trace:

```
panic: runtime error: slice bounds out of range [179264:0]
goroutine 9546228 [running]:
github.com/andybalholm/brotli.(*h5).FindLongestMatch(0xc005abc5a0, 0x0?, {0xc06d724002, 0x810007, 0x810007}, 0x7fffff, {0xc030a201c0, 0x10, 0x0?}, 0x0, ...)
        github.com/andybalholm/brotli/h5.go:169 +0x7ff
github.com/andybalholm/brotli.createBackwardReferences(0x10000, 0x0, {0xc06d724002, 0x810007, 0x810007}, 0x63e05d?, 0xc030a20058, {0x1bd2e48, 0xc005abc5a0}, {0xc030a201c0, ...}, ...)
        github.com/andybalholm/brotli/backward_references.go:77 +0x359
github.com/andybalholm/brotli.encodeData(0xc030a20028, 0x0, 0x83?)
        github.com/andybalholm/brotli/encode.go:844 +0xae7
github.com/andybalholm/brotli.encoderCompressStream(0xc030a20028, 0x1, 0xc000a06e68, 0xc000a06e98)
        github.com/andybalholm/brotli/encode.go:1190 +0x2d5
github.com/andybalholm/brotli.(*Writer).writeChunk(0xc030a20028, {0x0?, 0xd46220?, 0x1?}, 0xc030a20028?)
        github.com/andybalholm/brotli/writer.go:78 +0xb9
github.com/andybalholm/brotli.(*Writer).Flush(0x6c595d?)
        github.com/andybalholm/brotli/writer.go:97 +0x25
```

**Comment by andybalholm** [comment]
I think that's showing that the slice length is zero. That seems rather strange. Either there's memory corruption, or the call to Initialize was missed somehow…

**Comment by thaustad** [comment]
Thanks for taking a look. I do reuse the encoder and call Reset() before serving each document. It has worked perfectly for months and have have only seen this once and there have been no instabilities elsewhere in the program. I'll see if I can provoke this again.

**Comment by thaustad** [comment]
I had a Write/Flush race. Closing. Thanks for the library!
