### ISSUE TITLE
Build failure on 32 bits arches

### ISSUE THREAD

**Issue by eclipseo** [andybalholm/brotli#7]
Both on i686 and armv7 with Golang 1.12.6:

```
Testing    in: /builddir/build/BUILD/brotli-71eb68cc467c35a70c4b3d0c46b590260fe3f303/_build/src
         PATH: /builddir/build/BUILD/brotli-71eb68cc467c35a70c4b3d0c46b590260fe3f303/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/brotli-71eb68cc467c35a70c4b3d0c46b590260fe3f303/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X github.com/andybalholm/brotli/version.commit=71eb68cc467c35a70c4b3d0c46b590260fe3f303 -X github.com/andybalholm/brotli/version=0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: github.com/andybalholm/brotli
github.com/andybalholm/brotli
--- FAIL: TestDecodeFuzz (0.00s)
panic: runtime error: index out of range [-2] [recovered]
	panic: runtime error: index out of range [-2]
goroutine 88 [running]:
testing.tRunner.func1(0x58cb0000)
	/usr/lib/golang/src/testing/testing.go:874 +0x352
panic(0x56a80120, 0x58c163e0)
	/usr/lib/golang/src/runtime/panic.go:663 +0x180
github.com/andybalholm/brotli.TestDecodeFuzz(0x58cb0000)
	/builddir/build/BUILD/brotli-71eb68cc467c35a70c4b3d0c46b590260fe3f303/_build/src/github.com/andybalholm/brotli/brotli_test.go:322 +0x366
testing.tRunner(0x58cb0000, 0x56a9ecdc)
	/usr/lib/golang/src/testing/testing.go:909 +0xae
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:960 +0x2d3
exit status 2
FAIL	github.com/andybalholm/brotli	0.455s
```

**Comment by andybalholm** [comment]
When I saw the negative array index in the panic, I figured it would be some issue with pointer arithmetic that didn't translate correctly from C. But it turned out it was just an error in the testing code.
